### ISSUE TITLE
vmon.exe was not display the content of the virtual monitor

### ISSUE THREAD

**Issue by guozhi** [LinJiabang/remote-display#1]
hi,Lin
    i was follow your step4 ,installed everthing succeced,also i saw the "fresco logic proxy display adapter"
and the "ljb virtual monitor" under the "system devices" node which is in the device  manager view.
    and then i started vmon.exe ,nothing happened,even if i selected the "plugin" "open"menu.
    am i miss some sets to let the vmon.exe display the content of the virtual monitor.
thanks very mush!

**Comment by LinJiabang** [comment]
Hi GuoZhi,
If things don't work, try uninstall lci_proxykmd.inf , then follow the steps in

https://www.linkedin.com/pulse/usb-display-driver-demystified-part-2-jiabang-lin/
