### ISSUE TITLE
Driver certification issues

### ISSUE THREAD

**Issue by BattleAxeVR** [LinJiabang/remote-display#2]
Hey there, great project, it's the only one of its kind that works for me, I tried the indirect display driver from the Microsoft employee and it crashed my system. 

I did have to mod your build batch file a bit to get it to compile on my machine, but it fails at the certification step so I can't actually install a custom-built vmon driver, only your precompiled version. The vmon.exe file I built works fine with your precompiled vmon driver though. 

Your batch file has a hard coded Digisign .cer filename, so I tried to get my own but I can't figure out why it's not working. There are a lot of parameters and cert types.

Can you tell me, do you have to use a paid certificate authority? I'm OK with the user having to click "trust this driver" but right now, I can't get signtool to actually do its job.

I'm also confused about the differences between the various certificate authorities and which exact one is needed for this type of driver signing. Can you elaborate a bit on how you created your .cer file so that I can get this up and running with my own? 

Thanks!

**Comment by LinJiabang** [comment]
Hi,
Yes, we bought certificate from DigiCert.  A Digicert driver signing certificate should work for you.
