### ISSUE TITLE
Is the driver suitable for use under win8 and win10 systems?

### ISSUE THREAD

**Issue by luodh** [LinJiabang/remote-display#4]
Hi, is this driver suitable for use under win8 and win10 systems? What is the maximum resolution of the virtual display?

**Comment by LinJiabang** [comment]
hi luodh,

the driver was tested on win10 a year ago. I haven't tested it on win7 & win8. The driver should work from win7 to win10. Note that the lci_proxywddm.sys would downgrade your WDDM version to 2.1 if the inbox WDDM driver version is higher or above WDDM 2.2.

The maximum resolution is depended on the inbox GPU capability.  I've seen 4K resolution reported by other users. So, it should work at least for 3840 x 2160.  For resolution higher than this, you should try it yourself.

**Comment by luodh** [comment]
Thanks!
Does your driver work for different graphics cards? For example, I have a discrete graphics card from NVIDIA or AMD.

**Comment by LinJiabang** [comment]
@luodh : 
I think it should work on all graphics cards. The LCI_PROXYWDDM driver was tested and deployed for commercial use in Fresco Logic FL2000 driver. You should be able to use it without any surprise.

The "LCI_VMON" driver is for demo purpose only, and is NOT for commercial use. The idea is that you can implement your "virtual monitor" driver that talks to "LCI_PROXYWDDM" driver.
