### ISSUE TITLE
Windows on ARM, Support?

### ISSUE THREAD

**Issue by sidd-kishan** [LinJiabang/remote-display#8]
Please let us know when can we have an ARM64 driver for Windows on ARM. We can help you test we have Windows on Rasberry Pi setup. Please pursue it we at Windows on Rasberry Pi community will be glad to extend support in testing your drivers and tools for ARM64.

**Comment by LinJiabang** [comment]
hi @sidd-kishan ,  this project is kind of "out-of-date". This project is meaningful for pre-win10 OS. On Win10 RS1 and later, a new framework (indirect display) is supported by Microsoft, and we no longer need lci_proxykmd.sys for screen extension.  For Windows on ARM platform, go for "indirect display" framework solution.
